In [15]:
import numpy as np
from scipy.integrate import trapz
from scipy.integrate import quad

In [16]:
# Define the PDF function
def funf(x):
    λ, μ  = 2 , 1
    f = np.sqrt(λ / (2 * np.pi * x**3)) * np.exp(-λ / (2 * μ**2 * x) * (x - μ)**2)
    return f

In [17]:
# Define Rieman sum integration
def riemann(a, b, n_intervals):
    delta_x = (b - a) / n_intervals
    riemann_result = 0

    for i in range(n_intervals):
        x_i = (a + i) * delta_x
        f_i = funf(x_i)
        riemann_result += f_i * delta_x

    return riemann_result

In [18]:
# Define trapezoid
def trapezoid(a, b, n):
    h = (b - a) / n
    sum = 0

    for i in range(1, n):
        sum += 2*funf(a + i * h)
        integration = (h/2)*(funf(a)+ sum +funf(b))
    return integration

In [19]:
# Define romberg
def romberg(a, b, n):
    Rom = np.zeros(shape=(n,n))#initialise it to zero
    Rom[0, 0] = ((b - a) / 2) * (funf(a) + funf(b))
    for i in range(1, n):
        Rom[i, 0] = trapezoid(a, b, n)
        for j in range(1, i+1):
            Rom[i, j] = Rom[i, j-1] + ((Rom[i, j-1] - Rom[i-1, j-1]) / (4**(j) - 1))
    return Rom

In [20]:
#trapz and quad from scipy
def scipy (funf, a, b):
    x = np.linspace(a, b, num=100)
    f = funf(x)
    trap_result = trapz(f, x)
    quad_result, error = quad(funf, a, b)

    print(f"The result using trapz from scipy is {trap_result:.5f}")
    print('-------------------------------')
    print(f"The result using quad from scipy is {quad_result:.5f} with an error {error:.5f}")

In [21]:
#magic numbers
epsilon = 0.5e-6
a,b = epsilon , 50
n_intervals = 100 #riemann sum
n = 4 #trapezoid

print(f"The result using Romberg algorithm is the table below. \n{romberg(a, b, n)}")
print('-------------------------------')
print(f"The result using Riemann sum is {riemann(a, b, n_intervals):.5f}")
print('-------------------------------')
scipy (funf, a, b)

The result using Romberg algorithm is the table below. 
[[5.57299997e-23 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.05634465e-06 5.40845954e-06 0.00000000e+00 0.00000000e+00]
 [4.05634465e-06 4.05634465e-06 3.96620366e-06 0.00000000e+00]
 [4.05634465e-06 4.05634465e-06 4.05634465e-06 4.05777546e-06]]
-------------------------------
The result using Riemann sum is 1.01496
-------------------------------
The result using trapz from scipy is 1.01354
-------------------------------
The result using quad from scipy is 1.00000 with an error 0.00000
